#ifndef ENV_H_
#define ENV_H_

#define LBIN_ENV_ECHO "LBIN_ECHO"
#define LBIN_ENV_NO_HEADERS "LBIN_NO_HEADERS"
#define LBIN_ENV_IN "LBIN_IN"
#define LBIN_ENV_OUT "LBIN_OUT"
#define LBIN_ENV_BASE_PATH "LBIN_BASEPATH"
#define LBIN_ENV_FILE_PATH "LBIN_FILEPATH"
#define LBIN_ENV_NO_CHK_FILENAME "LBIN_NOFILENAMECHK"

#endif
